[shell]
program = "C:\\Windows\\System32\\wsl.exe ~"

[font]
size = 10
normal = { "family" = "RobotoMono Nerd Font", "style" = "Regular" }

[colors.primary]
background = "#000000"
foreground = "#BBBBBB"

[colors.selection]
background = "#B5D5FF"

[colors.cursor]
text = "0x0a0c10"
cursor = "#BBBBBB"

[colors.normal]
black = "#4C4C4C"
red = "#BB0000"
green = "#5FDE8F"
yellow = "#F3F167"
blue = "#276BD8"
magenta = "#BB00BB"
cyan = "#00DADF"
white = "#BBBBBB"

[colors.bright]
black = "#555555"
red = "#FF5555"
green = "#55FF55"
yellow = "#FFFF55"
blue = "#5555FF"
magenta = "#FF55FF"
cyan = "#55FFFF"
white = "#FFFFFF"
